spring:
  application:
    name: simplecloud-sso
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simplecloud?characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123
  jpa:
    hibernate:
    #      ddl-auto: create
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
     defaultZone: http://localhost:1001/eureka/
server:
  port: 1003

